# Generated by Django 3.2.9 on 2021-11-23 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField(max_length=5)),
                ('grade', models.CharField(choices=[('K', 'Kindergarten'), ('E', 'Elementary '), ('M', 'Middle School'), ('H', 'High School')], default='K', max_length=1)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_email', models.EmailField(max_length=100)),
                ('school_url', models.URLField()),
                ('notes', models.TextField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
