# Generated by Django 3.2.9 on 2021-11-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_classroom_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('notes', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='classroom',
            name='wishlists',
            field=models.ManyToManyField(to='main_app.Wishlist'),
        ),
    ]
