# Generated by Django 3.2.9 on 2021-11-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211123_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('notes', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='wishlists',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='notes',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.AddField(
            model_name='item',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom'),
        ),
    ]
