# Generated by Django 3.2.9 on 2021-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211129_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.URLField(max_length=300),
        ),
    ]
